"""
Security assessment report generation
"""

import json
from datetime import datetime
from typing import Dict, List, Any, Optional
from jinja2 import Template
from red_team_toolkit.utils import get_logger

logger = get_logger(__name__)


class ReportGenerator:
    """Generate professional security assessment reports"""

    HTML_TEMPLATE = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Security Assessment Report</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
                line-height: 1.6;
                color: #333;
            }
            .header {
                border-bottom: 3px solid #d9534f;
                padding-bottom: 20px;
                margin-bottom: 20px;
            }
            .header h1 {
                color: #d9534f;
                margin: 0;
            }
            .meta {
                font-size: 0.9em;
                color: #666;
            }
            .summary {
                background: #f5f5f5;
                padding: 15px;
                border-left: 4px solid #d9534f;
                margin: 20px 0;
            }
            .summary h2 {
                margin-top: 0;
            }
            .severity-critical { color: #d9534f; font-weight: bold; }
            .severity-high { color: #f0ad4e; font-weight: bold; }
            .severity-medium { color: #5bc0de; }
            .severity-low { color: #5cb85c; }
            .vulnerability {
                border: 1px solid #ddd;
                padding: 15px;
                margin: 15px 0;
                background: #fafafa;
            }
            .vulnerability h3 {
                margin-top: 0;
                color: #333;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
            }
            table th, table td {
                border: 1px solid #ddd;
                padding: 12px;
                text-align: left;
            }
            table th {
                background-color: #f5f5f5;
                font-weight: bold;
            }
            .footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #ddd;
                font-size: 0.9em;
                color: #666;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Security Assessment Report</h1>
            <div class="meta">
                <p><strong>Target:</strong> {{ target }}</p>
                <p><strong>Date:</strong> {{ date }}</p>
                <p><strong>Assessor:</strong> Red Team Toolkit</p>
            </div>
        </div>

        <div class="summary">
            <h2>Executive Summary</h2>
            <p>This security assessment identified <strong>{{ total_vulnerabilities }}</strong> vulnerability findings.</p>
            <table>
                <tr>
                    <th>Severity</th>
                    <th>Count</th>
                </tr>
                {% for severity, count in severity_breakdown.items() %}
                <tr>
                    <td class="severity-{{ severity.lower() }}">{{ severity }}</td>
                    <td>{{ count }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        <h2>Findings</h2>
        {% for vulnerability in vulnerabilities %}
        <div class="vulnerability">
            <h3>{{ vulnerability.type }}</h3>
            <p><strong>Severity:</strong> <span class="severity-{{ vulnerability.severity.lower() }}">{{ vulnerability.severity }}</span></p>
            <p><strong>Description:</strong> {{ vulnerability.description }}</p>
            {% if vulnerability.recommendation %}
            <p><strong>Recommendation:</strong> {{ vulnerability.recommendation }}</p>
            {% endif %}
            {% if vulnerability.details %}
            <p><strong>Details:</strong></p>
            <pre>{{ vulnerability.details }}</pre>
            {% endif %}
        </div>
        {% endfor %}

        <div class="footer">
            <p>This report contains confidential information. Use responsibly and only on authorized targets.</p>
            <p>Generated by Red Team Toolkit</p>
        </div>
    </body>
    </html>
    """

    def __init__(self, target: str, assessor: str = "Red Team Toolkit"):
        """
        Initialize report generator

        Args:
            target: Target of assessment
            assessor: Assessor name/team
        """
        self.target = target
        self.assessor = assessor
        self.vulnerabilities: List[Dict] = []
        self.metadata: Dict[str, Any] = {}

    def add_vulnerability(self, vulnerability: Dict):
        """
        Add vulnerability to report

        Args:
            vulnerability: Vulnerability dictionary
        """
        self.vulnerabilities.append(vulnerability)

    def add_vulnerabilities(self, vulnerabilities: List[Dict]):
        """
        Add multiple vulnerabilities to report

        Args:
            vulnerabilities: List of vulnerability dictionaries
        """
        self.vulnerabilities.extend(vulnerabilities)

    def set_metadata(self, key: str, value: Any):
        """
        Set report metadata

        Args:
            key: Metadata key
            value: Metadata value
        """
        self.metadata[key] = value

    def _get_severity_breakdown(self) -> Dict[str, int]:
        """
        Get breakdown of vulnerabilities by severity

        Returns:
            Dictionary of severity counts
        """
        breakdown = {}
        for vuln in self.vulnerabilities:
            severity = vuln.get("severity", "Unknown")
            breakdown[severity] = breakdown.get(severity, 0) + 1
        return breakdown

    def generate_html(self, filepath: str):
        """
        Generate HTML report

        Args:
            filepath: Output filepath for HTML report
        """
        template = Template(self.HTML_TEMPLATE)

        context = {
            "target": self.target,
            "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "total_vulnerabilities": len(self.vulnerabilities),
            "severity_breakdown": self._get_severity_breakdown(),
            "vulnerabilities": self.vulnerabilities,
        }

        html_content = template.render(context)

        try:
            with open(filepath, "w") as f:
                f.write(html_content)
            logger.info(f"HTML report generated: {filepath}")
        except Exception as e:
            logger.error(f"Error generating HTML report: {e}")

    def generate_json(self, filepath: str):
        """
        Generate JSON report

        Args:
            filepath: Output filepath for JSON report
        """
        report = {
            "metadata": {
                "target": self.target,
                "assessor": self.assessor,
                "date": datetime.now().isoformat(),
                **self.metadata,
            },
            "summary": {
                "total_vulnerabilities": len(self.vulnerabilities),
                "severity_breakdown": self._get_severity_breakdown(),
            },
            "vulnerabilities": self.vulnerabilities,
        }

        try:
            with open(filepath, "w") as f:
                json.dump(report, f, indent=2, default=str)
            logger.info(f"JSON report generated: {filepath}")
        except Exception as e:
            logger.error(f"Error generating JSON report: {e}")

    def generate_csv(self, filepath: str):
        """
        Generate CSV report

        Args:
            filepath: Output filepath for CSV report
        """
        try:
            import csv

            with open(filepath, "w", newline="") as f:
                if not self.vulnerabilities:
                    logger.warning("No vulnerabilities to export")
                    return

                fieldnames = self.vulnerabilities[0].keys()
                writer = csv.DictWriter(f, fieldnames=fieldnames)

                writer.writeheader()
                writer.writerows(self.vulnerabilities)

            logger.info(f"CSV report generated: {filepath}")
        except Exception as e:
            logger.error(f"Error generating CSV report: {e}")

    def generate_summary(self) -> Dict:
        """
        Get report summary

        Returns:
            Report summary dictionary
        """
        return {
            "target": self.target,
            "assessor": self.assessor,
            "date": datetime.now().isoformat(),
            "total_vulnerabilities": len(self.vulnerabilities),
            "severity_breakdown": self._get_severity_breakdown(),
            "metadata": self.metadata,
        }

    def get_vulnerabilities_by_severity(self, severity: str) -> List[Dict]:
        """
        Get vulnerabilities filtered by severity

        Args:
            severity: Severity level

        Returns:
            List of vulnerabilities
        """
        return [v for v in self.vulnerabilities if v.get("severity") == severity]
